# Generated by Django 3.1.2 on 2020-10-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='refers_to',
            field=models.ManyToManyField(null=True, related_name='_employee_refers_to_+', to='backend.Employee'),
        ),
    ]
