# Generated by Django 3.1.2 on 2020-10-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20201003_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='projects',
            field=models.ManyToManyField(blank=True, to='backend.Project'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='refers_to',
            field=models.ManyToManyField(blank=True, related_name='_employee_refers_to_+', to='backend.Employee'),
        ),
    ]
