# Generated by Django 3.1.2 on 2020-10-03 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20201004_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='coffee_math',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='backend.employee'),
        ),
    ]
